# Generated by Django 4.1.5 on 2023-05-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок новости')),
                ('description', models.TextField(default=None, null=True, verbose_name='Текст новости')),
                ('data', models.DateField(null=True, verbose_name='Дата публикации')),
                ('img', models.ImageField(upload_to='image/%Y', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории услуги')),
                ('text_details', models.TextField(max_length=1000, verbose_name='Описание категории')),
                ('img', models.ImageField(upload_to='service/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=30, verbose_name='Название подкатегории услуги')),
                ('text_under_category', models.TextField(blank=True, max_length=1000)),
                ('service_cat', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='dj_app.service', verbose_name='Выбрать категорию услуг')),
            ],
            options={
                'verbose_name': 'Подкатегория услуг',
                'verbose_name_plural': 'Подкатегории услуг',
                'ordering': ['name_of_category'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='TheService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=100, verbose_name='Название конкретной услуги')),
                ('price', models.IntegerField(verbose_name='Цена BYN')),
                ('service', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='dj_app.servicecategory', verbose_name='Выбрать подкатегорию услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name_of_service'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-адрес')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app.post', verbose_name='Публикация')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text_comments', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
