# Generated by Django 4.1.5 on 2023-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0005_sale_data_sale_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='img',
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия сотрудника')),
                ('img', models.ImageField(upload_to='worker/', verbose_name='Изображение')),
                ('field', models.ManyToManyField(help_text='Выберите категорию услуг', to='dj_app.servicecategory', verbose_name='Категория услуг')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
