# Generated by Django 4.1.5 on 2023-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0006_remove_sale_img_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promo_info',
            field=models.TextField(default=None, null=True, verbose_name='Текст превью новости'),
        ),
    ]
