# Generated by Django 4.1.5 on 2023-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0007_post_promo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='promo_info',
            field=models.TextField(default=None, max_length=300, null=True, verbose_name='Текст превью новости (до 300 символов)'),
        ),
    ]
