# Generated by Django 4.1.5 on 2023-05-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0009_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
