# Generated by Django 4.1.5 on 2023-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0010_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='worker/', verbose_name='Фото наших работ')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='choices',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(default='img.jpg', max_length=500, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
