# Generated by Django 4.1.5 on 2023-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0011_images_remove_order_choices_order_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='our_works/', verbose_name='Фото наших работ'),
        ),
    ]
