# Generated by Django 4.1.5 on 2023-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0012_alter_images_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок новости')),
                ('promo_info', models.TextField(default=None, max_length=300, null=True, verbose_name='Текст превью новости (до 300 символов)')),
                ('description', models.TextField(default=None, null=True, verbose_name='Текст новости')),
                ('data', models.DateField(null=True, verbose_name='Дата публикации')),
                ('img', models.ImageField(upload_to='post_suggestions', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Предложенная новость',
                'verbose_name_plural': 'Предложенные новости',
            },
        ),
    ]
