# Generated by Django 4.1.5 on 2023-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0013_postsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsuggestion',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
