# Generated by Django 4.1.5 on 2023-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0014_alter_postsuggestion_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='sale/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postsuggestion',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsuggestion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок новости'),
        ),
    ]
