# Generated by Django 4.1.5 on 2023-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0015_sale_img_alter_postsuggestion_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Заказ обраюотан?'),
        ),
    ]
